### ISSUE TITLE
Cannot find any module matching the provided specification 'phabricator'

### ISSUE THREAD

**Issue by jimmybrancaccio** [bitnami/bitnami-docker-phabricator#154]
**Description**

It appears after an upgrade there's an issue with Apache and it finding or using the correct document root. Here's some output which I am seeing in the logs:

```
nami    ERROR Cannot find any module matching the provided specification 'phabricator',
INFO  ==> Starting gosu... ,
Starting Apache...,
[Mon Aug 17 09:17:32.019784 2020] [ssl:warn] [pid 44] AH01909: internal.myvideogamelist.com:443:0 server certificate does NOT include an ID which matches the server name,
[Mon Aug 17 09:17:32.055696 2020] [ssl:warn] [pid 44] AH01909: internal.myvideogamelist.com:443:0 server certificate does NOT include an ID which matches the server name,
[Mon Aug 17 09:17:32.070453 2020] [core:warn] [pid 44] AH00098: pid file /opt/bitnami/apache/tmp/httpd.pid overwritten -- Unclean shutdown of previous Apache run?,
[Mon Aug 17 09:17:32.073485 2020] [mpm_prefork:notice] [pid 44] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.21 configured -- resuming normal operations,
[Mon Aug 17 09:17:32.073517 2020] [core:notice] [pid 44] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND',
nami    TRACE Error: Cannot find any module matching the provided specification 'phabricator',
    at Manager.search (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:158:13),
    at Command.callback (/opt/bitnami/nami/cli/nami-app.js:555:39),
    at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:527:30),
    at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:750:14),
    at Module.load (module.js:566:32),
    at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19),
    at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17),
    at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10)
```

Of note, I use Traefik in front of this container, it does an https redirect and handles the SSL certificates.

I haven't had any issues until now with this so I am not sure what broke what.

**Steps to reproduce the issue:**

1. Spin up a container using `bitnami/phabricator:latest`.
2. Visit the URL which you've configured.
3. Note that you see - "**It works!**" instead of the Phabricator installation.

**Describe the results you received:**

I see "**It works!**" instead of the Phabricator installation.

**Describe the results you expected:**

I expect to see the Phabricator instance.

**Additional information you deem important (e.g. issue happens only occasionally):**

This seems to happen consistently. Everything had been working normally, but it appears some upgrade broke something in Apache.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 51
  Running: 51
  Paused: 0
  Stopped: 0
 Images: 112
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 94.36GiB
 Name: yoshi
 ID: SLJV:IM45:L5KV:OGKV:A4PN:U47F:AYLU:OAUW:GK7N:XYNT:FCTG:P32L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: jimmyb
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

N/A

**Comment by andresbono** [comment]
Hi @jimmybrancaccio, thanks for opening this issue. You mention that this happens after an upgrade. Can you tell us more about how are you doing this upgrade process? Are you keeping the container volumes and updating the container image?

**Comment by jimmybrancaccio** [comment]
Hi @andresbono! The container data is kept (it's just a file path on the system) and the image is updated. I use watchtower to keep things updated.

**Comment by andresbono** [comment]
Can you give us the specific versions that are causing the issue? You can check the versions by executing:

```
docker exec -it CONTAINER env | grep BITNAMI_IMAGE_VERSION
```

**Comment by jimmybrancaccio** [comment]
Here ya go!

`BITNAMI_IMAGE_VERSION=2020.31.0-debian-10-r2`

**Comment by andresbono** [comment]
Hi @jimmybrancaccio, we tried to reproduce your issue with docker-compose. But is working well.

- `docker-compose up`
- `docker-compose down`
- Update image
- `docker-compose up`

We tried the following images:
- `docker.io/bitnami/phabricator:2020.29.0-debian-10-r0`
- `docker.io/bitnami/phabricator:2020.31.0-debian-10-r2`

Can you share the complete log of the container to see if there is other piece of information that could lead us to find the source of the issue?

**Comment by jimmybrancaccio** [comment]
Hey @andresbono, absolutely, here's the container logs. It feels like something isn't happening right with the VirtualHost for Apache and is thus sending me into the default DocumentRoot.

```
Welcome to the Bitnami phabricator container,
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator,
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues,
,
INFO  ==> Starting gosu... ,
Starting Apache...,
[Mon Aug 17 09:17:32.019784 2020] [ssl:warn] [pid 44] AH01909: internal.myvideogamelist.com:443:0 server certificate does NOT include an ID which matches the server name,
[Mon Aug 17 09:17:32.055696 2020] [ssl:warn] [pid 44] AH01909: internal.myvideogamelist.com:443:0 server certificate does NOT include an ID which matches the server name,
[Mon Aug 17 09:17:32.070453 2020] [core:warn] [pid 44] AH00098: pid file /opt/bitnami/apache/tmp/httpd.pid overwritten -- Unclean shutdown of previous Apache run?,
[Mon Aug 17 09:17:32.073485 2020] [mpm_prefork:notice] [pid 44] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.21 configured -- resuming normal operations,
[Mon Aug 17 09:17:32.073517 2020] [core:notice] [pid 44] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND',
nami    ERROR Cannot find any module matching the provided specification 'phabricator',
nami    TRACE Error: Cannot find any module matching the provided specification 'phabricator',
    at Manager.search (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:158:13),
    at Command.callback (/opt/bitnami/nami/cli/nami-app.js:555:39),
    at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:527:30),
    at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:750:14),
    at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17),
    at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12),
    at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
172.18.0.200 - - [17/Aug/2020:22:21:55 -0500] "GET / HTTP/1.1" 200 45,
172.18.0.200 - - [17/Aug/2020:22:21:55 -0500] "GET /favicon.ico HTTP/1.1" 404 196,
172.18.0.200 - - [18/Aug/2020:13:53:20 -0500] "GET /file/data/k4rfhxovzs3cao6pp67l/PHID-FILE-o3h3uqz7itadyitjf7vr/profile HTTP/1.1" 404 196,
172.18.0.200 - - [18/Aug/2020:13:53:23 -0500] "GET /file/data/p2usrl3gumlmfboi3ea4/PHID-FILE-asx5tw6h63eerrjvhmpg/profile HTTP/1.1" 404 196,
172.18.0.200 - - [18/Aug/2020:13:53:24 -0500] "GET /file/data/p2usrl3gumlmfboi3ea4/PHID-FILE-asx5tw6h63eerrjvhmpg/profile HTTP/1.1" 404 196,
172.18.0.200 - - [18/Aug/2020:13:53:31 -0500] "GET /file/data/5gkz36eu3jhjrmylthok/PHID-FILE-zaru7lpcub2abwzihbee/ad697e-alphanumeric_lato-white_V.png-0%2C0%2C0%2C0.png HTTP/1.1" 404 196,
172.18.0.200 - - [18/Aug/2020:13:53:32 -0500] "GET /file/data/5gkz36eu3jhjrmylthok/PHID-FILE-zaru7lpcub2abwzihbee/ad697e-alphanumeric_lato-white_V.png-0%2C0%2C0%2C0.png HTTP/1.1" 404 196,
172.18.0.200 - - [18/Aug/2020:13:53:40 -0500] "GET /file/data/ztl7bqknxv7wyzepoij3/PHID-FILE-ter6joyktme7raq7tou6/eb957f-alphanumeric_aleo-white_V.png-255%2C255%2C255%2C0.4.png HTTP/1.1" 404 196,
172.18.0.200 - - [19/Aug/2020:02:55:06 -0500] "GET / HTTP/1.1" 200 45
```

**Comment by andresbono** [comment]
Hi @jimmybrancaccio, the `/root` directory is supposed to be part of the container image, if you mount it as a volume, it could lead into issues.

In particular, to force the issue that you are facing, we modified the integrity of the `/root/.nami/registry.json` file:

```diff
         "com.bitnami.phabricator": {
             "id": "com.bitnami.phabricator",
-            "name": "phabricator",
+            "name": "phabricatorXX",
             "version": "2020.29",
             "revision": "0",
             "installedAsRoot": true,
```

That way, we get:

```
phabricator_1  | INFO  ==> Starting gosu...
phabricator_1  | Starting Apache...
phabricator_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 192.168.160.3. Set the 'ServerName' directive globally to suppress this message
phabricator_1  | [Mon Aug 24 11:53:00.088615 2020] [ssl:warn] [pid 44] AH01909: 192.168.160.3:443:0 server certificate does NOT include an ID which matches the server name
phabricator_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 192.168.160.3. Set the 'ServerName' directive globally to suppress this message
phabricator_1  | [Mon Aug 24 11:53:00.113412 2020] [ssl:warn] [pid 44] AH01909: 192.168.160.3:443:0 server certificate does NOT include an ID which matches the server name
phabricator_1  | [Mon Aug 24 11:53:00.126099 2020] [mpm_prefork:notice] [pid 44] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.21 configured -- resuming normal operations
phabricator_1  | [Mon Aug 24 11:53:00.126135 2020] [core:notice] [pid 44] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
phabricator_1  | nami    ERROR Cannot find any module matching the provided specification 'phabricator'
phabricator_1  | nami    TRACE Error: Cannot find any module matching the provided specification 'phabricator'
phabricator_1  |     at Manager.search (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:158:13)
phabricator_1  |     at Command.callback (/opt/bitnami/nami/cli/nami-app.js:555:39)
phabricator_1  |     at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:527:30)
phabricator_1  |     at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:750:14)
phabricator_1  |     at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17)
phabricator_1  |     at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12)
phabricator_1  |     at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19)
phabricator_1  |     at Module._compile (module.js:653:30)
phabricator_1  |     at Object.Module._extensions..js (module.js:664:10)
phabricator_1  |     at Module.load (module.js:566:32)
```

That looks like the error message that you reported.

For reference: https://github.com/bitnami/nami-core/blob/96c7afbfb72051b47bcab94a4ff81fb38b170f87/lib/manager.js#L158

**Comment by jimmybrancaccio** [comment]
Hi @andresbono, thanks for taking a look and finding the root cause! It's very odd, I could have sworn I was mounting a local dir to /root in the container before and it was working fine. For the time being I've just mounted /root/.bash_history to the container and all seems happy now. Thank you again for your time in helping figure this one out! 😄

**Comment by andresbono** [comment]
Thanks for confirming it!
